[package]
name = "zip"
version = "0.6.6"
authors = ["Mathijs van de Nes <git@mathijs.vd-nes.nl>", "Marli Frost <marli@frost.red>", "Ryan Levick <ryan.levick@gmail.com>"]
license = "MIT"
repository = "https://github.com/zip-rs/zip.git"
keywords = ["zip", "archive"]
description = """
Library to support the reading and writing of zip files.
"""
edition = "2021"
rust-version = "1.59.0"

[dependencies]
aes = { version = "0.8.2", optional = true }
async-stream = "0.3.5"
byteorder = "1.4.3"
bytes = "1"
bzip2 = { version = "0.4.3", optional = true }
constant_time_eq = { version = "0.1.5", optional = true }
crc32fast = "1.3.2"
flate2 = { version = "1.0.23", default-features = false, optional = true }
futures-core = "0.3.28"
futures-util = "0.3.28"
hmac = { version = "0.12.1", optional = true, features = ["reset"] }
indexmap = "2"
parking_lot = { version = "0.12.1", features = ["arc_lock"] }
pbkdf2 = {version = "0.11.0", optional = true }
sha1 = {version = "0.10.1", optional = true }
static_assertions = "1.1.0"
time = { version = "0.3.7", optional = true, default-features = false, features = ["std"] }
tokio = { version = "1.32.0", features = ["rt", "io-util", "sync", "fs", "macros"] }
tokio-stream = "0.1.14"
tokio-util = { version = "0.7.9", features = ["io", "io-util"] }
zstd = { version = "0.11.2", optional = true }

[target.'cfg(any(all(target_arch = "arm", target_pointer_width = "32"), target_arch = "mips", target_arch = "powerpc"))'.dependencies]
crossbeam-utils = "0.8.8"

[dev-dependencies]
bencher = "0.1.5"
criterion = { version = "0.5", features = ["async_tokio"] }
getrandom = "0.2.5"
once_cell = "1.18.0"
sha3 = "0.10.8"
tempfile = "3.8.0"
time = { version = "0.3.7", features = ["formatting", "macros"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
tokio-test = "0.4.3"
walkdir = "2.3.2"

[features]
aes-crypto = [ "aes", "constant_time_eq", "hmac", "pbkdf2", "sha1" ]
deflate = ["flate2/rust_backend"]
deflate-miniz = ["flate2/default"]
deflate-zlib = ["flate2/zlib"]
unreserved = []
default = ["aes-crypto", "bzip2", "deflate", "time", "zstd"]

[[bench]]
name = "read_entry"
harness = false

[[bench]]
name = "read_metadata"
harness = false

[[bench]]
name = "extract"
harness = false

[profile.release]
strip                   = false
debug                   = true
# lto                     = true
